module.exports = {

    //HEADERS
    HEADER_OS_TYPE: "x-header-os-type",
    HEADER_APP_VERSION: "x-header-app-version",
    HEADER_AUTH_TOKEN: "x-header-authtoken",
    HEADER_REFRESH_TOKEN: "refreshtoken",

    //API RESPONSE MESSAGES
    NO_CONTENT: "No Record Found.",
    OTP_SUCCESS: "OTP generated successfully.",
    OTP_VERIFICATION: "OTP verified successfully.",
    REGISTERED_MSG: "Registered Successfully",
    USER_EXISTS: "User has already been registered.",
    ROLE_EXISTS: "Role already exists.",
    USER_NOT_EXISTS: "No User found with the details provided.",
    STORE_EXISTS: "Store name already exists.",
    STORE_SETTINGS_EXISTS: "Store Setting name already exists.",
    CATEGORY_EXISTS: "Category already exists.",
    SUBCATEGORY_EXISTS: "Sub category already exists.",
    STORE_CREATION_FAILED: "Cannot create Store.",
    STORE_NOT_EXISTS: "Couldn't find Store details with provided info.",
    ROLE_NOT_EXISTS: "Couldn't find Role details with provided info.",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    MISSING_OS_TYPE: "No os-type header provided",
    MISSING_APP_VERSION: "No x-app-version header provided",
    INVALID_OS_TYPE: "Invalid os-type header provided",
    NEW_APP_VERSION: "New version of Application is available.Please update the app.",
    MISSING_ROLE: "No role provided in header",
    MISSING_REFRESH_TOKEN: "No refresh token provided.",
    MISSING_ACCESS_TOKEN: "No access token provided.",
    UNAUTHORISED: "Un-Authorized user.",
    MISSING_USERNAME: "No Username provided.",
    MISSING_PASSWORD: "No Password provided.",
    MISSING_DEVICE_TOKEN: "No Device token provided.",
    WRONG_PASSWORD: "Incorrect Email Address or Password. Please enter valid credentials and try again.",
    RESTRICTED_ACCESS: "No Access for this user.",
    INCORRECT_USERNAME: "User not found.",
    BAD_REQUEST: "Missing mandatory parameters as per DB schema.",
    INVALID_USERNAME: "Invalid username.",
    INVALID_PASSWORD: "Invalid password.",
    INVALID_OTP: "Invalid OTP.",
    USER_DEACTIVATED: "Account not active or deactivated. Please contact Nxt-Order Admin.",
    LOGGED_OUT: "Successfully Logged oyt.",
    STORE_DEACTIVATED: "Store account is not Activated or has been deactivated.",
    EMPLOYEES_MISSING: "Employees not found in the Store.",
    OFFER_DEACTIVATED: "Offer removed successfully.",
    MISSING_PRODUCT: "Product is invalid",
    FILE_MISSING: "File is missing",
    INDUSTRY_CREATION_FAILED: "Cannot create Industry.",
    INDUSTRY_DEACTIVATED: "Industry account is not Activated or has been deactivated.",
    INDUSTRY_EXISTS: "Industry name already exists.",
    PLAN_EXISTS: "Plan name already exists.",
    PLAN_NOT_EXISTS: "No Plan found with the details provided.",

};